# Generated by Django 5.1.1 on 2024-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='current_employee_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='size_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='total_employee_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['name'], name='users_uploa_name_3983fe_idx'),
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['domain'], name='users_uploa_domain_71b9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['year_founded'], name='users_uploa_year_fo_22528c_idx'),
        ),
    ]
