version: '3'

services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 cmmi_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cmmi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/sites-available/cmmi
      - "8090:8090"
    depends_on:
      - web

volumes:
  postgres_data:
